version: '3'
services:
  web:
    image: fluvip/vip_hi:1
    command: bash -c 'bin/webpack-dev-server --watch --progress --color & bundle exec rails s -p 3000 -b "0.0.0.0"'
    ports:
      - 3000:3000
      - 8080:8080
    depends_on:
      - postgres
      - selenium
      - elasticsearch
    volumes:
      - .:/vip_hi
    tty: true
    stdin_open: true

  postgres:
    image: postgres:11.2
    volumes:
      - postgres_vip_data:/var/lib/postgresql/data

  selenium:
    image: selenium/standalone-chrome-debug
    ports:
      - 4444:4444
      - 5900:5900
    shm_size: 512M

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.1.0
    container_name: es01
    environment:
      - node.name=es01
      - cluster.initial_master_nodes=es01
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms750m -Xmx750m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    cap_add:
      - IPC_LOCK
    volumes:
      - esdata01:/usr/share/elasticsearch/data
    ports:
      - 9200:9200

volumes:
  postgres_vip_data:
    driver: local
  esdata01:
    driver: local
