version: '3'
services:
  web:
    image: fluvip/vip_hi:1
    command: bash -c 'bin/webpack --watch --progress --color & bundle exec rails s -p 3000 -b "0.0.0.0"'
    ports:
      - 3000:3000
      - 8080:8080
    depends_on:
      - postgres
    volumes:
      - .:/vip_hi
    tty: true
    stdin_open: true

  postgres:
    image: postgres:11.2
    volumes:
      - postgres_vip_data:/var/lib/postgresql/data

volumes:
  postgres_vip_data:
    driver: local
