default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: postgres
  username: postgres

development:
  <<: *default
  database: vip_hi_development

test:
  <<: *default
  database: vip_hi_test
production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
